name: WasteManagementNetwork
version: "1.0"

caliper:
  blockchain: ethereum

ethereum:
  url: "http://127.0.0.1:8545"
  contractDeployerAddress: "0x123456789abcdef123456789abcdef123456789a"
  contractDeployerAddressPrivateKey: "YOUR_PRIVATE_KEY"
  gasLimit: 6721975
  gasPrice: 20000000000
  contracts:
    - id: WasteManagement
      path: ./contracts/WasteManagement.sol
      language: solidity
      deploy:
        from: "0x123456789abcdef123456789abcdef123456789a"
        args:
          - "InitialArg1"
          - 1000
        gasLimit: 5000000
